[package]
name = "magical-bitcoin-wallet"
version = "0.1.0"
edition = "2018"
authors = ["Riccardo Casatta <riccardo@casatta.it>", "Alekos Filini <alekos.filini@gmail.com>"]

[dependencies]
magical-macros = { path = "./macros" }
log = "^0.4"
bitcoin = { git = "https://github.com/sgeisler/rust-bitcoin.git", branch = "2020-06-bip32-derive-more", features = ["use-serde"] }
# miniscript = { git = "https://github.com/afilini/rust-miniscript.git", rev = "779d164" }
miniscript = { path = "../rust-miniscript" }
serde = { version = "^1.0", features = ["derive"] }
serde_json = { version = "^1.0" }

# Optional dependencies
sled = { version = "0.31.0", optional = true }
# electrum-client = { version = "0.2.0-beta.1", optional = true }
electrum-client = { path = "../rust-electrum-client", optional = true }
reqwest = { version = "0.10", optional = true, features = ["json"] }
futures = { version = "0.3", optional = true }
clap = { version = "2.33", optional = true }
base64 = { version = "^0.11", optional = true }

# Platform-specific dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "0.2", features = ["rt-core"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
async-trait = "0.1"

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
# hwi = { version = "0.1", optional = true }
hwi = { path = "../rust-hwi", optional = true }

[features]
minimal = []
compiler = ["miniscript/compiler"]
default = ["key-value-db", "electrum"]
electrum = ["electrum-client"]
esplora = ["reqwest", "futures"]
key-value-db = ["sled"]
cli-utils = ["clap", "base64"]
hardware-wallets = ["hwi", "base64"]

[dev-dependencies]
lazy_static = "1.4"
rustyline = "6.0"
dirs = "2.0"
env_logger = "0.7"
rand = "0.7"

[[example]]
name = "repl"
required-features = ["cli-utils"]
[[example]]
name = "psbt"
required-features = ["cli-utils"]
[[example]]
name = "parse_descriptor"

[[example]]
name = "miniscriptc"
path = "examples/compiler.rs"
required-features = ["compiler"]

# Provide a more user-friendly alias for the REPL
[[example]]
name = "magic"
path = "examples/repl.rs"
required-features = ["cli-utils"]

