on: [push]

name: Code Coverage

jobs:
  tarpaulin-codecov:
    name: Tarpaulin to codecov.io
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true # FIXME issue #168
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: tarpaulin
        uses: actions-rs/tarpaulin@v0.1.2
        with:
          version: '0.15.0'
          args: --features all-keys,cli-utils,compiler,esplora,compact_filters --run-types Tests,Doctests --exclude-files "testutils/*"

      - name: codecov.io
        uses: codecov/codecov-action@v1.0.14
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
